[package]
name = "analisar"
version = "0.2.1"
authors = ["rfm <r@robertmasen.pizza>"]
edition = "2018"
license = "MIT"
description = "A Lua parser for Rust"

[dependencies]
bstr = "0.2"
lex_lua = "0.1"
log = "0.4"
pretty_env_logger = "0.4"
